# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
            in_memory:
                    memory:
                            users:
                                serhii:
                                    password: $2y$13$GTUGCpxvZbqSkyQ.FiZBUOfbnidsEXs5AqtkWMZxhGoYD.Si7KE7S
                                    roles: "ROLE_USER"
                                admin:
                                    password: $2y$13$GTUGCpxvZbqSkyQ.FiZBUOfbnidsEXs5AqtkWMZxhGoYD.Si7KE7S
                                    roles: "ROLE_ADMIN"

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            stateless: true
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
