movie_index:
    path:     /
    defaults: { _controller: "MifoBundle:Admin:index" }
    methods:  GET

movie_show:
    path:     /{id}/show
    defaults: { _controller: "MifoBundle:Admin:show" }
    methods:  GET

admin_movie_new:
    path:     /new
    defaults: { _controller: "MifoBundle:Admin:new" }
    methods:  [GET, POST]

movie_edit:
    path:     /{id}/edit
    defaults: { _controller: "MifoBundle:Admin:edit" }
    methods:  [GET, POST]

movie_delete:
    path:     /{id}/delete
    defaults: { _controller: "MifoBundle:Admin:delete" }
    methods:  DELETE
